apiVersion: v1
kind: Service
metadata:
  name: fantaco-customer-service
  labels:
    app: fantaco-customer-main
spec:
  type: ClusterIP
  selector:
    app: fantaco-customer-main
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
